drugrecord/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'),namespace='users')),
    path('drug/', include(('drugs.urls', 'drugs'),namespace='drugs')),
]

drugs/urls.py
from django.urls import path
from drugs import views

urlpatterns = [
    path('add/',views.AddView.as_view(),name='add'),
    #path('<str:username>/',views.UserDetailsView.as_view(),name='details'),
]

users/urls.py
from django.urls import path,include
from users import views

urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('dashboard/',views.DashboardView.as_view(),name='dashboard'),
    path('<str:username>/',views.UserDetailsView.as_view(),name='details'),
]

drugs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Drugs(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    #profile=models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    name=models.CharField(max_length=30)
    num_boxs=models.IntegerField()
    #count_gelcaps_of_box=models.IntegerField()
    num_gelcaps=models.IntegerField()#number of caps
    mg=models.IntegerField()#mg of gelcaps
    dose=models.IntegerField()#dosis/dia

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    create_account=models.DateTimeField(auto_now_add=True)
    birthday=models.DateTimeField(null=True)

drugs/forms.py
from django import forms
from drugs.models import Drugs

class AddForm(forms.ModelForm):
    """user=models.ForeignKey(User, on_delete=models.CASCADE)
    profile=models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    name=forms.CharField(max_length=30)
    num_boxs=forms.IntegerField()
    #count_gelcaps_of_box=forms.IntegerField()
    num_gelcaps=forms.IntegerField()#number of caps
    mg=forms.IntegerField()#mg of gelcaps
    dose=forms.IntegerField()#dosis/dia"""

    class Meta:
        model=Drugs
        fields=('name','num_boxs','num_gelcaps','mg','dose')

users/forms.py
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignUpForm(forms.Form):
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    #birthday=forms.DateTimeField()
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


drugs/views.py
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from drugs.forms import AddForm

# Create your views here.

class AddView(LoginRequiredMixin,CreateView):
    template_name='drugs/add.html'
    form_class=AddForm
    
    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        #context['profile'] = self.request.user.profile
        #context['count_gelcaps_of_box']=context['num_gelcaps']
        return context

users/views.py
from users.forms import SignUpForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import FormView,DetailView,ListView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class SignUpView(FormView):
    template_name='user/signup.html'
    form_class=SignUpForm
    success_url = reverse_lazy('users:login')

    def form_valid(self,form):
        form.save()
        return super().form_valid(form)


class UserDetailsView(LoginRequiredMixin,DetailView):
    template_name = ".html"
    slug_field='username'
    slug_url_kwarg='username'
    queryset=User.objects.all()
    context_object_name='user'

class DashboardView(LoginRequiredMixin,ListView):
    template_name='user/dashboard.html'
    model=User
    context_object_name='user'


class LoginView(auth_views.LoginView):
    template_name='user/login.html'

class LogoutView(LoginRequiredMixin,auth_views.LogoutView):
    template_name='user/logged_out.html'


templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset='UTF-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% block header_container %}
        {% endblock %}

        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <div class="container mt-5">
            {% block body_container %}
            {% endblock body_container %}
        </div>

    </body>
</html>

templates/drugs/add.html
{% block head_container %}
    <title>Add new drug</title>
{% endblock head_container %}

{% block body_container %}
    <form action="{% url 'drugs:add' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary btn-block mt-5" type="submit">New drug!</button>
    </form>
{% endblock body_container %}

templates/user/dashboard.html
{% extends 'base.html' %}

{% block head_container %}
  <title>dashboard {{request.user.username}}</title>
{% endblock head_container %}

{% block body_container %}
    <div class="row mt-4">
        <div class="col-sm-4">
            <h2>
                {{request.user.first_name}}
                {{request.user.last_name}}

            </h2>
        </div>
    </div>
    <a href="{% url 'users:logout' %}">by!</a>
    
{% endblock body_container %}

templates/user/login.html
{% extends "base.html" %}

{% block head_container %}
<title>Login</title>
{% endblock%}

{% block body_container %}
    <div class="w-50 mx-auto">
        {% if form.errors %}
            <p class="alert alert-danger">
                Your username and password didn't match. Please try again.
            </p>
        {% endif%}
    
        <form method="POST" action="{% url "users:login" %}">
            {% csrf_token %}
    
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Username" name="username" />
            </div>
    
            <div class="form-group">
                <input class="form-control" type="password" placeholder="Password" name="password" />
            </div>
    
    
            <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    
        </form>
    
        <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>
    </div>

{% endblock %}

templates/user/signup.html
{% extends 'base.html' %}

{% block head_container %}
    <title>Sing Up</title>
{% endblock head_container %}

{% block body_container %}
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>
{% endblock body_container %}